### ISSUE TITLE
何故ダブルアンダースコア？

### ISSUE THREAD

**Issue by unoemon** [igatake/Traffic-Light#13]
https://github.com/igatake/Traffic-Light/blob/ebdc4307e7ae3d26d5db3702719f9ae024b89f2a/index.html#L14

**Comment by igatake** [comment]
自分に教えてくださってた先輩がこのような書き方だったので、そのままでした、、
アンダースコア一つか別の書き方の方がいいでしょうか？

**Comment by unoemon** [comment]
なるほど！
まあ好みの問題もありますが（キャメルとスネーク）
ここはアンダースコア1つでいきましょう！＼(^o^)／

**Comment by igatake** [comment]
かしこまりました！
